# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Events"
url = "events/"
weight = 2

[[main]]
name = "Devpost"
url = "https://axe-hacks-2022.devpost.com/"
weight = 3

[[main]]
name = "Get Involved"
url = "get-involved/"
weight = 3

[[main]]
name = "FAQ"
url = "faq/"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 5

# footer menu left
[[footer_left]]
name = "ACM-Women"
url = "https://linktr.ee/ACMWuncc"

[[footer_left]]
name = "Girls Who Code"
url = "https://gwc-uncc.github.io/myportfolio/"

# [[footer_left]]
# name = "Pricing"
# url = "pricing/"


# # footer menu middle
# [[footer_middle]]
# name = "Pricing"
# url = "pricing/"

[[footer_middle]]
name = "Devpost"
url = "https://axe-hacks-2022.devpost.com/"

# [[footer_middle]]
# name = "Events"
# url = "blog/"

[[footer_middle]]
name = "Hackathon Rules"
url = "hackathon-rules/"

#footer menu right
[[footer_right]]
name = "FAQs"
url = "faq/"

[[footer_right]]
name = "Contact Us"
url = "contact/"