#################### default parameters ################################
logo = "images/logo.png"
footer_logo = "images/footer-logo.png"
logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "Official website for Axe Hacks 2022"
author = "bluelotus03"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# from languages.toml file
title = "Axe Hacks"
weight = 1
########### footer content ##########
footer_menu_left = "Hosts"
footer_menu_middle = "Hackathon"
footer_menu_right = "Support"
footer_content = "A fun, beginner-friendly introduction to hackathons."
# copyright
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Register"
link = "https://bit.ly/axe-hacks-form"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################
# [[social]]
# title = "facebook"
# icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
# link = "#"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/axe_hacks"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/axe.hacks/"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/axe-hacks/"

[variables]
# all colors are defined here: assets/scss/style.scss
# primary color
primary_color = "#381A89"
# light colored versions of rows
light = "#D5F3F1"
